### ISSUE TITLE
在manfiest文件中加入FileProvider注册会构建失败build fail,怎么解决呢?

### ISSUE THREAD

**Issue by LLhon** [honjane/fileProviderDemo#1]

**Comment by honjane** [comment]
1.检查下provider包名是否正确
2.xml文件是否存在

把错误日志贴一下呢

**Comment by honjane** [comment]
@LLhon

**Comment by LLhon** [comment]
Information:Gradle tasks [:AndFix:generateDebugSources, :AndFix:generateDebugAndroidTestSources, :AndFix:mockableAndroidJar, :AndFix:prepareDebugUnitTestDependencies, :PushSDK:generateDebugSources, :PushSDK:generateDebugAndroidTestSources, :PushSDK:mockableAndroidJar, :PushSDK:prepareDebugUnitTestDependencies, :ViewPagerIndicator_Library:generateDebugSources, :ViewPagerIndicator_Library:generateDebugAndroidTestSources, :ViewPagerIndicator_Library:mockableAndroidJar, :ViewPagerIndicator_Library:prepareDebugUnitTestDependencies, :app:generateAndroidscDebugSources, :app:generateAndroidscDebugAndroidTestSources, :app:prepareAndroidscDebugUnitTestDependencies, :app:mockableAndroidJar, :jcvideoplayer-lib:generateDebugSources, :jcvideoplayer-lib:generateDebugAndroidTestSources, :jcvideoplayer-lib:mockableAndroidJar, :jcvideoplayer-lib:prepareDebugUnitTestDependencies, :kefu-easeui:generateDebugSources, :kefu-easeui:generateDebugAndroidTestSources, :kefu-easeui:mockableAndroidJar, :kefu-easeui:prepareDebugUnitTestDependencies, :library:generateDebugSources, :library:generateDebugAndroidTestSources, :library:mockableAndroidJar, :library:prepareDebugUnitTestDependencies, :photoSelector:generateDebugSources, :photoSelector:mockableAndroidJar, :photoSelector:prepareDebugUnitTestDependencies, :photoSelector:generateDebugAndroidTestSources]
Error:Execution failed for task ':app:processAndroidscDebugManifest'.
> Manifest merger failed with multiple errors, see logs
Information:BUILD FAILED
Information:Total time: 3.746 secs
Information:1 error


包名是正确的,xml文件是存在的.我目前的解决办法就是自定义一个类继承FileProvider

**Comment by honjane** [comment]
@LLhon 
你可以在编译时候打印出错误日志，这个日志没有看出问题点在哪里，只知道执行task processAndroidscDebugManifest出错，运行gradle assembleDebug --info 或者gradlew processDebugManifest --stacktrace 看能不能打印出具体的位置。


自定义FileProvider可以的话，也是一个不错的解决办法。

**Comment by linq8261** [comment]
设置了 root-path ，问题依然没有解决。

`java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/tencent/MicroMsg/WeiXin/mmexport1499045742961.jpg`

华为荣耀8

**Comment by linq8261** [comment]
原来是我设置错了，把provider放到app里面就行了，放到其它module都不行

**Comment by honjane** [comment]
@AudienL  是的provider对应有app的包名，module里面不一样吧
