### ISSUE TITLE
虽然打开照相机了，但是照片并没有被正确存储

### ISSUE THREAD

**Issue by AlexXiu** [honjane/fileProviderDemo#2]
onActivityResult 中返回的 resultCode 是 RESULT_CANCELED，而不是RESULT_OK。

**Comment by AlexXiu** [comment]
麻烦大神指教一下，谢谢

**Comment by honjane** [comment]
06-15 10:47:44.964 450-450/com.honjane.providerdemo I/main: to do
06-15 10:48:28.822 450-450/com.honjane.providerdemo I/main: to do

测试了两次 没有出现你说的情况 。。。。

你是什么手机，版本，什么情况下出现的，错误日志贴一下

**Comment by honjane** [comment]
6.0以上需要动态申请android.permission.WRITE_SETTINGS
