### ISSUE TITLE
拍照成功了 但是返回的resultcode=0(cancel)

### ISSUE THREAD

**Issue by kakaxicm** [honjane/fileProviderDemo#3]
如题

**Comment by honjane** [comment]
使用的设备型号，系统版本是多少 6.0以上需要自己申请android.permission.WRITE_SETTINGS运行时权限，这个demo演示工具类，没有动态申请权限 @kakaxicm

**Comment by kakaxicm** [comment]
系统7.0 手机是谷歌的Pixel

**Comment by honjane** [comment]
@kakaxicm 你申请权限再试下
